apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: webapp-namespace
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: database
      protocol: TCP
      port: 1433
      targetPort: 1433

---

apiVersion: v1
kind: Service
metadata:
  name: database-lb
  namespace: webapp-namespace
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433