apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  namespace: webapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: rkristijan/webapp:latest
          env:
            - name: dbHost
              value: database-service
            - name: dbName
              value: webappdb
            - name: dbSaPassword
              valueFrom:
                secretKeyRef:
                  key: SA_PASSWORD
                  name: secrets
            - name: ASPNETCORE_URLS
              value: http://+:80/
    